<a href="https://colab.research.google.com/github/AmrHassanKhalaf/ITI_Camp_AI/blob/main/2_Python_Numpy_Exercises_with_hints.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python NumPy Exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name `np` and print the numpy version and the configuration (★☆☆)

`Hint: import … as` and `np.__version__, np.show_config)`

In [1]:
import numpy as np
print(np.__version__)
print(np.show_config())

2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name

#### 2. Convert a list of numeric value into a one-dimensional NumPy array (★☆☆)
`💡 hint: numpy.array`

In [3]:
li=[1,2,3,4,5]
np.array(li)

array([1, 2, 3, 4, 5])

#### 3. Create a null vector of size 9 (★☆☆)
`💡 hint: np.zeros`

In [5]:
n_v=np.zeros(9)
n_v

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)
`💡 hint: size, itemsize`

In [7]:
print(n_v.size)
n_v.itemsize

9


8

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)
`💡hint: np.info`

In [11]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 12 but the sixth value which is 1 (★☆☆)
`💡hint: array[12]`

In [13]:
ide=np.zeros(12)
ide[5]=1
ide

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 20 to 59 (★☆☆)
`💡hint: arange`

In [14]:
vec=np.arange(20,60)
vec

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59])

#### 8. Reverse a vector (first element becomes last) (★☆☆)
`💡hint: array[::-1]`

In [15]:
rev=vec[::-1]
rev

array([59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43,
       42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26,
       25, 24, 23, 22, 21, 20])

#### 9. Create a 3x3 matrix with values ranging from 12 to 20 (★☆☆)
`💡hint: reshape`

In [16]:
res=np.arange(12,21).reshape(3,3)
res

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Find indices of non-zero elements from [3,7,0,0,9,0] (★☆☆)
`💡hint: np.nonzero`

In [17]:
n_z=np.nonzero([3,7,0,0,9,0])
n_z

(array([0, 1, 4]),)

#### 11. Create a 4x4 identity matrix (★☆☆)
`💡hint: np.eye`

In [18]:
ey=np.eye(4)
ey

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### 12. Create a 2x2x2 array with random values (★☆☆)
`💡hint: np.random.random`

In [19]:
rand=np.random.random((2,2,2))
rand

array([[[0.01186754, 0.11355329],
        [0.41074119, 0.90271542]],

       [[0.77540927, 0.57510481],
        [0.1841823 , 0.69527444]]])

#### 13. Create a 9x9 array with random values and find the minimum and maximum values (★☆☆)
`💡hint: min, max`

In [21]:
rand_max=np.random.random((9,9))
print(rand_max)
print(rand_max.max())
print(rand_max.min())

[[0.82776409 0.74775241 0.98776175 0.74409678 0.0306787  0.77844124
  0.71826762 0.25898883 0.21147247]
 [0.46302603 0.38473795 0.24754374 0.30065601 0.14151203 0.95937218
  0.79092346 0.17576598 0.42500164]
 [0.4119057  0.7356542  0.34718221 0.62250266 0.45175952 0.2870512
  0.191964   0.29968072 0.8927267 ]
 [0.85083699 0.36276262 0.69637168 0.39364591 0.58050746 0.64635506
  0.90777659 0.91333879 0.0063458 ]
 [0.70296469 0.57605174 0.52758502 0.66973324 0.7831323  0.2647903
  0.06000414 0.35751389 0.44896417]
 [0.20107584 0.20330742 0.30654648 0.94449887 0.3999482  0.40018383
  0.82355513 0.55910895 0.37784717]
 [0.56705366 0.27234028 0.54919469 0.28724947 0.22051949 0.31473045
  0.37714725 0.63209387 0.92418509]
 [0.28016333 0.29458497 0.79462583 0.2650287  0.96630019 0.06098962
  0.4311081  0.57414135 0.26997785]
 [0.28773527 0.7191216  0.8412718  0.11876959 0.12099859 0.46854671
  0.4222335  0.61801117 0.77603901]]
0.9877617488887027
0.006345803820837714


#### 14. Create a random vector of size 20 and find the mean value (★☆☆)
`💡hint: mean`

In [22]:
vec=np.random.random(20)
print(vec)
print(vec.mean())

[0.33377692 0.70441805 0.98755565 0.23486166 0.10879578 0.11474746
 0.78521959 0.60473114 0.39888926 0.78572744 0.49305312 0.53033829
 0.87898675 0.09365708 0.04100123 0.40589568 0.2265057  0.01883029
 0.4916731  0.00101608]
0.41198401423461617


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
`💡hint: array[1:-1, 1:-1]`

In [23]:
d2=np.ones((5,5))
d2[1:-1,1:-1]=0
d2

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
`💡hint: np.pad`

In [24]:
pord=np.pad(d2,pad_width=1,mode='constant',constant_values=0)
pord

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```
`💡hint: NaN = not a number, inf = infinity`

In [25]:
res=0 * np.nan
print(res)
res1=np.nan == np.nan
print(res1)
res2=np.inf > np.nan
print(res2)

nan
False
False


#### 18. Create a 6x6 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`💡hint: np.diag`

In [26]:
dia=np.diag(1+np.arange(4),k=-1)
dia

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 6x6 matrix and fill it with a checkerboard pattern (★☆☆)
`💡hint: array[::2]`

In [27]:
patt=np.zeros((6,6),dtype=int)
patt[1::2,::2]=1
patt[::2,1::2]=1
patt

array([[0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0]])

#### 20. Consider a (8,9,10) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
`💡hint: np.unravel_index`

In [28]:
x=np.unravel_index(100,(8,9,10))
x

(np.int64(1), np.int64(1), np.int64(0))

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
`💡hint: np.tile`

In [29]:
checker=np.array([[0,1],[1,0]])
result=np.tile(checker,(4,4))
result

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 6x6 random matrix (★☆☆)
`💡hint: (x -mean)/std`

In [30]:
normal=np.random.random((6,6))
normal=(normal-np.mean(normal))/np.std(normal)
normal

array([[ 0.14140741, -1.71602067,  1.45111305,  0.44049219, -1.90817479,
        -1.295451  ],
       [-0.34238565, -0.96470872,  0.32443864, -1.63507814,  1.17242504,
         1.05230103],
       [-0.8448854 , -0.75687738,  0.66571151,  0.12608462, -1.21086106,
         0.81738307],
       [ 0.66773877, -0.58255956, -1.37642841, -0.33595541, -0.05556193,
        -0.85558579],
       [ 0.34326659,  1.32185598,  1.28612654,  1.22651305,  0.35403439,
        -0.08720208],
       [ 1.11374363, -1.4151737 ,  1.35446297,  0.99867459, -0.14382369,
         0.66896031]])

#### 23. find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements. (★☆☆)

In [31]:
fi=np.array([1,2,3,4,5])
print(fi.size)
print(fi.itemsize)
print(fi.nbytes)

5
8
40


#### 24. Multiply a 6x3 matrix by a 3x4 matrix (real matrix product) (★☆☆)
`💡hint: np.dot` or `np.ones`

In [32]:
milt=np.dot(np.ones((6,3)),np.ones((3,4)))
milt

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
`💡hint: >, <`

In [33]:
dive_1d=np.arange(10)
dive_1d[(dive_1d>3) & (dive_1d<8)]*=-1
dive_1d

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

#### 26. What is the output of the following script? (★☆☆)
```python

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [34]:
scr=sum(range(5),-1)
print(scr)
from numpy import *
scr1=sum(range(5),-1)
print(scr1)

9
10


#### 27. Write a Python program compare two arrays using numpy (★☆☆)
```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [35]:
py=np.array([1,2])
py1=np.array([4,5])
print(np.greater(py,py1))
print(np.greater_equal(py,py1))

[False False]
[False False]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```
Consider an integer vector a
```python
a**a
a << a >> 2
a <- a
1j*a
a/1/1
a<a>a
```

In [36]:
res=np.array(0) / np.array(0)
print(res)
res1=np.array(0) // np.array(0)
print(res1)

nan
0


/tmp/ipython-input-2196731462.py:1: RuntimeWarning: invalid value encountered in divide
  res=np.array(0) / np.array(0)
/tmp/ipython-input-2196731462.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  res1=np.array(0) // np.array(0)


#### 29. How to round away from zero a float array ? (★☆☆)
`💡hint: np.uniform, np.copysign, np.ceil, np.abs, np.where`

In [37]:
round_away=np.random.uniform(-10,+10,10)
print(round_away)
print(np.copysign(np.ceil(np.abs(round_away)),round_away))

[ 6.81846605  6.2985722   9.54568561 -3.22037546 -1.62065646  9.05276907
 -7.76520811  9.28429398 -0.49739905 -4.36235347]
[ 7.  7. 10. -4. -2. 10. -8. 10. -1. -5.]


#### 30. How to find common values between two arrays? (★☆☆)
`💡hint: np.intersect1d`

In [38]:
common=np.random.randint(0,10,10)
commo=np.random.randint(0,10,10)
print(np.intersect1d(common,commo))

[0 4 5 7]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)
`💡hint: np.seterr, np.errstate`

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```
`💡hint: imaginary number`

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)
`💡hint: np.datetime64, np.timedelta64`

#### 34. How to get all the dates corresponding to the month of January 2016? (★★☆)
`💡hint: np.arange(dtype=datetime64['D'])`

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
`💡hint: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=)`

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)
`💡hint: %, np.floor, astype, np.trunc`

#### 37. Create a 3x3 matrix with row values ranging from 0 to 2 (★★☆)
`💡hint: np.arange`

#### 38. Consider a generator function that generates 9 integers and use it to build an array (★☆☆)
`💡hint: np.fromiter`

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
`💡hint: np.linspace`

#### 40. Create a random vector of size 10 and sort it (★★☆)
`💡hint: sort`

#### 41. How to sum a small array faster than np.sum? (★★☆)
`💡hint: np.add.reduce`

#### 42. Consider two random array A and B, check if they are equal (★★☆)
`💡hint: np.allclose, np.array_equal`

#### 43. Make an array immutable (read-only) (★★☆)
`💡hint: flags.writeable`

#### 44. Consider a random 5x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
`💡hint: np.sqrt, np.arctan2`

#### 45. Create random vector of size 5 and replace the maximum value by 0 (★★☆)
`💡hint: argmax`

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)
`💡hint: np.meshgrid`

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)
`💡hint: np.subtract.outer`

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)
`💡hint: np.iinfo, np.finfo, eps`

#### 49. How to print all the values of an array? (★★☆)
`💡hint: np.set_printoptions`

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)
`💡hint: argmin`

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)
`💡hint: dtype`

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)
`💡hint: np.atleast_2d, T, np.sqrt`

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?
`💡hint: view and [:] =`

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```
`💡hint: np.genfromtxt`

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)
`💡hint: np.ndenumerate, np.ndindex`

#### 56. Generate a generic 2D Gaussian-like array (★★☆)
`💡hint: np.meshgrid, np.exp`

#### 57. How to randomly place e elements in a 2D array? (★★☆)
`💡hint: np.put, np.random.choice`

#### 58. Subtract the mean of each row of a matrix (★★☆)
`💡hint: mean(axis=,keepdims=)`

#### 59. How to sort an array by the nth column? (★★☆)
`💡hint: argsort`

#### 60. How to tell if a given 2D array has null columns? (★★☆)
`💡hint: any, ~`

#### 61. Find the nearest value from a given value in an array (★★☆)
`💡hint: np.abs, argmin, flat`

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)
`💡

#### 63. Create an array class that has a name attribute (★★☆)
`💡hint: class method`

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)
`💡hint: np.bincount | np.add.at`

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)
`💡hint: np.bincount`

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)
`💡hint: np.unique`

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)
`💡hint: sum(axis=(-2,-1))`

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)
`💡hint: np.bincount`

#### 69. How to get the diagonal of a dot product? (★★★)
`💡hint: np.diag`

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)
`💡hint: array[::4]`

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)
`💡hint: array[:, :, None]`

#### 72. How to swap two rows of an array? (★★★)
`💡hint: array[[]] = array[[]]`

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)
`💡hint: repeat, np.roll, np.sort, view, np.unique`

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)
`💡hint: np.repeat`

#### 75. How to compute averages using a sliding window over an array? (★★★)
`💡hint: np.cumsum`

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)
`💡hint: from numpy.lib import stride_tricks`

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)
`💡hint: np.logical_not, np.negative`

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)
`💡hint: minimum maximum`

#### 81. Consider an array a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)
`💡hint: stride_tricks.as_strided`

#### 82. Compute a matrix rank (★★★)
`💡hint: np.linalg.svd`

#### 83. How to find the most frequent value in an array?
`💡hint: np.bincount, argmax`

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)
`💡hint: stride_tricks.as_strided`

#### 85. Create a 2D array subclass such that a[i,j] == a[j,i] (★★★)
`💡hint: class method`

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)
`💡hint: np.tensordot`

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)
`💡hint: np.add.reduceat`

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)
`💡hint: np.argsort | np.argpartition`

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)
`💡hint: np.indices`

#### 91. How to create a record array from a regular array? (★★★)
`💡hint: np.core.records.fromarrays`

#### 92. Consider a large vector A, compute A to the power of 3 using 3 different methods (★★★)
`💡hint: np.power, *, np.einsum`

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)
`💡hint: np.where`

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)
`💡hint: np.unpackbits`

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)
`💡hint: np.ascontiguousarray | np.unique`

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)
`💡hint: np.einsum`

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?
`💡hint: np.cumsum, np.interp`

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)
`💡hint: np.logical_and.reduce, np.mod`

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)
`💡hint: np.percentile`